### ISSUE TITLE
您好，我想问一下，我这边会报错，这种情况是啥原因呀

### ISSUE THREAD

**Issue by aAalert** [No4l/Burp4SSRF#1]
java.lang.RuntimeException: caqfyvsfjmz6m4tqxup1sk47kyqoed.burpcollaborator.net
	at burp.i5g.makeHttpRequest(Unknown Source)
	at burp.hn6.makeHttpRequest(Unknown Source)
	at burp.b78.makeHttpRequest(Unknown Source)
	at burp.b78.makeHttpRequest(Unknown Source)
	at burp.Correlator.<init>(BurpExtender.java:181)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.h44.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.RuntimeException: caqfyvsfjmz6m4tqxup1sk47kyqoed.burpcollaborator.net
	at burp.i5g.makeHttpRequest(Unknown Source)
	at burp.hn6.makeHttpRequest(Unknown Source)
	at burp.b78.makeHttpRequest(Unknown Source)
	at burp.b78.makeHttpRequest(Unknown Source)
	at burp.Correlator.<init>(BurpExtender.java:181)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at burp.h44.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by No4l** [comment]
看起来是访问不到burpcollaborator.net，后续我再加入一个功能，可以用户自己选择DNSLOG
